networks:
  observability: # Named to encompass the whole stack.

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yml
    ports:
      - "${LOKI_PORT:-3100}:3100"
    networks:
      - observability
    volumes:
      - "${LOKI_CONFIG_FILE}:/etc/loki/loki-config.yml:ro"
      - "${LOKI_DATA}:/loki"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'
      - '--storage.tsdb.retention.size=2GB'
      - '--web.enable-remote-write-receiver'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    networks:
      - observability
    volumes:
      - "${PROMETHEUS_CONFIG_FILE}:/etc/prometheus/prometheus.yml:ro"
      - "${PROMETHEUS_DATA}:/prometheus"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "472"
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    networks:
      - observability
    volumes:
      # Added your explicit grafana.ini file
      - "${GRAFANA_INI}:/etc/grafana/grafana.ini:ro"
      - "${GRAFANA_DATA}:/var/lib/grafana"
    restart: always

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "${ALLOY_PORT:-12345}:12345"
      - "${ALLOY_LISTEN_PORT:-5140}:5140/udp"
      - "${ALLOY_SURICATA_PORT:-5141}:5141/udp"
    networks:
      - observability
    group_add:
      - "${ADM_GRP}"
    volumes:
      - "${ALLOY_CONFIG_FILE}:/etc/alloy/config.alloy:ro"
      - "${ALLOY_GEOIP_DB}:/etc/alloy/GeoLite2-City.mmdb:ro"
      - "${ALLOY_DATA}:/var/lib/alloy/data"
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /proc:/proc:ro
      - /var/log:/var/log:ro
    restart: always
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      # Whitelist only what Alloy needs
      - CONTAINERS=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      # Explicitly deny destructive requests
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - observability
    restart: always
