all:
    children:
        routers:
            hosts:
                Portal_Ansible:
                Bedroom_AP:
                Hallway_AP:
                Bathroom_AP:
        fallback:
            hosts:
                Fallback_AP:
                Xtra_AP:
            vars:
                ansible_user: root
