# --- Global Setup ---

transaction_log {{TRANSACTION_LOG}}
preserve_hour_of_day {{PRESERVE_HOUR_OF_DAY}}
preserve_day_of_week {{PRESERVE_DAY_OF_WEEK}}
{{SSH_IDENTITY_CONF}}
{{SSH_USER_CONF}}

# --- Volume / Target Setup ---

snapshot_create {{SNAPSHOT_CREATE}}
volume {{MOUNT_LOCATION}}
   subvolume {{TARGET_SUBVOL}}
   incremental {{INCREMENTAL}}
   snapshot_preserve_min {{SNAPSHOT_PRESERVE_MIN}}
   snapshot_preserve {{SNAPSHOT_PRESERVE_HOURLY}} {{SNAPSHOT_PRESERVE_DAILY}} {{SNAPSHOT_PRESERVE_WEEKLY}} {{SNAPSHOT_PRESERVE_MONTHLY}} {{SNAPSHOT_PRESERVE_YEARLY}}

   target {{SECONDARY_MOUNT_LOCATION}}
   target_preserve_min {{SECONDARY_PRESERVE_MIN}}
   target_preserve {{TARGET_PRESERVE_HOURLY}} {{TARGET_PRESERVE_DAILY}} {{TARGET_PRESERVE_WEEKLY}} {{TARGET_PRESERVE_MONTHLY}} {{TARGET_PRESERVE_YEARLY}}
 
