#ENC[AES256_GCM,data:Q2sk7x0cQlkDGqf62tzlvL7dcWbR7cvnOHlqKu6mf4sbWicgIQ==,iv:cp9OMoBjFCMlCmrQH2c13J2L+wWiJEymMCNDd1FvKM0=,tag:PVDvQm32zyGXsZukEHOgjA==,type:comment]
ansible_become_password: ENC[AES256_GCM,data:7h4XS0+wCJmdEBiWxyK/s97h8KJj,iv:OFC/chEAMZCmS92IaDyN1zaH0QPhGr8OGmdKxuW80uA=,tag:hdsleVeErDV3Wab7ammUBQ==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:ronvjhkxaXESqgJm0L46Kt0qiFhNVg==,iv:D/bw8uFuWLoy8XbYOFxFrThfCzsUlhzfBlU8ECL6q48=,tag:kL1XgDngIsG3IGqU2KYp9w==,type:str]
ansible_host: ENC[AES256_GCM,data:hQcim7W3vdjtnlE=,iv:z5X3oSI6dAnhRGEvYGi/Y80c3zcBQEGA65D6EDrMRHw=,tag:6cz1yI2BfFeMlPTgee/mlQ==,type:str]
ansible_port: ENC[AES256_GCM,data:KQw=,iv:8Z8E6iWCTGA1ibjBOWCFZsn2hivIbHnko6dWJijzkf0=,tag:tXWpoT95nfE6Z0FoDrpDBA==,type:int]
ansible_user: ENC[AES256_GCM,data:K6nWdA==,iv:X9nJ1C+P73qubC23TN/PE/PywaZhi42rRf7xLTX1K3U=,tag:KpfMnv2RDYMgZHg/QhVDcw==,type:str]
computer_role: ENC[AES256_GCM,data:70+mlLi1,iv:exz7WQJxj17q2XhSINBBWlgibDbU9hiyPt2GtduDj+E=,tag:qZU2xwnKpPRkfScmt50t8g==,type:str]
computer_ou: ENC[AES256_GCM,data:2UVXRC4k89a0V2i2BcMrG9WrXuxgoL2yauJddfI/laeK09t0I0kpS/bGnKPrm6wzzQZYsxYs731f0c3n,iv:bpXa+5+5QFnj/QNtEKdPfIIqc3/h2S9LmjbPoHfmZAs=,tag:yQX1N6cydbNRDw0Z8+0jFA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ3lDTE9adDR5RkdvWU00
            TVhPdEJqbU9wcDhVMUFmekJWUGI1MCtTMVRjCjEwWkZPb3FyNkpoZEFaRjhoNkI3
            RjVRT3gyR2NpNmNhQlBNUGtJYXcydkkKLS0tIFFFbGdNZkRKeGxoR0lCakhMVzVW
            ZzhsWm44aUd2WGl1bWpNZjUyVngvVDQKCLfuulH4yTWl1xIFow4Rl0u9y6AZWdbX
            g2lkEIkFkG+C6t5/aCnYp5WywkyWHTCuvZZQ/gqadGSlKXDmhA8dKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1srxf8entezg03y8n550g24w4se7gm7kdzzltcxfhckq7lek93vfsu2rpnw
    lastmodified: "2026-07-26T03:52:54Z"
    mac: ENC[AES256_GCM,data:WhKyuSpvIq0u8x2yqmTocOnRf8PvcDxQy7QgfEzX+fhbJWnXxjrNMz1ZIlfpCpLLxrft9aiy8kBatfBZ2q8ChX54uisra29hEPeShT5EPxMG+lb+dH6pni05ZYosdlIKfaDB7i80HE0R7cFGAHz2UrQ3MAMWrywv2jF5How5KO0=,iv:2g0aOzZJ/PHcpK+4U4xAy14iRsUdpU9B2o5bYLtTFes=,tag:WyuqIl+ZeZ0VLfeptejliw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
