[checkupstream]
command:/usr/local/bin/opnsense-check_package_upstream_version.sh
parameters:
type:script
message:Checking locked packages against upstream repositories
description:Custom: Check Upstream Locked Packages
