#ENC[AES256_GCM,data:W1Xrx+eyENnjm+S938HbXR+0oP+OZD2VhOAb+cS4PvBeWuZl,iv:akmEY1cZj6Zx+h5KcjfVK+Nr/UkS551PBk2c10pIPoQ=,tag:Oc7Nm0kHl10fWbCGmQFrrA==,type:comment]
#ENC[AES256_GCM,data:ZT3yxNMa5w3UgWEIELu3vcJLMh7rcPhRUzMygKklFfY1fxZg,iv:Fg5UMS5YHxPAUBMVKYEL4PZfFas9TxMtZ69gi/fnFK4=,tag:Oa67/3V8OoB563rPbeL6bQ==,type:comment]
root_password: ENC[AES256_GCM,data:sP75qKD3bns+2Majw8LCRfUto5/gXyik0SLxFd/dL6viBEubQv33tWBI0xTGInD0TJbxAEVmB6rv0hGrL3fzkg==,iv:s1gBypHKfs7eIl9TTl10fWb3tc3WF2XlxWl1HGIpRow=,tag:tuOcHKdLFlaE5MFBajad6w==,type:str]
ansible_private_key_file: ENC[AES256_GCM,data:N6aE9IkR8UGgnoc1eV0Oh4MQ6YD3375PUpiNRnXP73tZ5cIyKtXs4w==,iv:ugoEuiauLCjFG2uk/E5HTSR2k2x066lvmtBcjw8byxc=,tag:07I+YONrBX1+PTxRmaMOKA==,type:str]
ansible_host: ENC[AES256_GCM,data:ogocAcx1RBaoL2K9O9bOhg==,iv:S0qTF9P5X3eum3DG00A90Fmw2u+Sjee4/8x0rtCQt7I=,tag:3oZ0RlM9acGAkONtRiVy+A==,type:str]
request_ip: ENC[AES256_GCM,data:Ap3QcOmNV5ErGQ==,iv:NOuuiPzKklRmEGugeVc+gJU9IX7QsYioLbhz4mPVoOA=,tag:mdccORiMKI480XbjdmyrVw==,type:str]
ansible_port: ENC[AES256_GCM,data:FNDJd78=,iv:aFSwZnYzApMQTmaaIPEuwPrJCFxZGVVqNxnIxY3e7Zw=,tag:62Bwamt8+nmDzqUb93aLgw==,type:int]
ansible_user: ENC[AES256_GCM,data:oWE3Cw==,iv:8PdNG0XqyZdKwEHJEEcY4x9Ldyh0hADPeu4d1MtG+bo=,tag:vyjE3amYexJYSMCpHPkPMw==,type:str]
ansible_transfer_method: ENC[AES256_GCM,data:bsEj,iv:vIHZcv1VzwGYst/OJmRDExcUz5p+fCs/MwJdnm0vbJY=,tag:Sphfq9IABq0iy7mRBlQllA==,type:str]
ansible_scp_extra_args: ENC[AES256_GCM,data:LIU=,iv:lHdUCrLw9tlspzOx8HAPz+VnV1S/CdbH0W/EIvb8XS8=,tag:WhELRlJkr2AOmArCEpzebw==,type:str]
node_role: ENC[AES256_GCM,data:WH85Es3OLw==,iv:WF0PXB6FQUQ69KqERt2Djw1ynR7o6vNH8nD/csHqpEo=,tag:HwuR39cI9G5yTW8NXXN/Cg==,type:str]
#ENC[AES256_GCM,data:f6vLuG+Q,iv:B4qc/aHdzKhG8whXH4AMNWyZcMNW6PmlLEHegQTsaeU=,tag:A4/0RIjIdfuft4sIi7dLrQ==,type:comment]
blink_name: ENC[AES256_GCM,data:xfKwNiysAk5yGmCv,iv:n3O2vPP8+kVWs/PSrHE+qCJsDvQFMlLRxrc7IQPkVEo=,tag:dulP3cjV4dzgVdS67EhGpw==,type:str]
color: ENC[AES256_GCM,data:dNsPeEgAoRFM,iv:UXY2c70fPGBJFHb+z3UkjcdEhjEyLUO+OsKKRoGzVC8=,tag:C6dNSupCxvUiIkiw6W5HQw==,type:str]
interface: ENC[AES256_GCM,data:eBe5Vw==,iv:IxELAZhLeswcus1gTMrCf460pXrVYDg68mP20Xq7u+c=,tag:+pUebk/QjTat9Z6Iw5cTqw==,type:str]
trigger: ENC[AES256_GCM,data:8Q1jIkFL,iv:xqwK8fF8F9UTKdSfCN0tUqmP49D4wEzI6yegfI3ZklM=,tag:cfsFJ3W08VWFbgLq4f2+XQ==,type:str]
change_uci_state: ENC[AES256_GCM,data:JWGt,iv:0k2m/vOuDAppSH802e13wW11jZtYM3vqcu08Ltp9qGA=,tag:LyEEu1iVPxw5jMwv5Y6vfw==,type:str]
led_mode: ENC[AES256_GCM,data:2U+o5CWxyFk=,iv:GqRktXya9hfkM/3qYW2/+beicO3PRe1Q6AztS6kptwg=,tag:G3Cs6XgU0PZOPfaiAC0WwQ==,type:str]
led_modes:
    - ENC[AES256_GCM,data:Rf8=,iv:yY/sBzFjULi7aLYLc5KOmOjGKa2TvpNAhVaVrw9s/40=,tag:wZb6rAPOMdXkXdtbvUnmlA==,type:str]
    - ENC[AES256_GCM,data:7b4=,iv:CHfK3paOSYSqDu16UTU18LYXn2x1bXObPbyGm9ia8nE=,tag:PxT5Gd5z4XMMJYVKFd3BxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKL1Q3STZtQzVkTmVINWNp
            VVd1Mk0rc2xWd09mRGJJRGVId1FpcDBZVlNBCjlQT2pXbUJXWWlqUldYeEdKSExw
            TVVtak16VFdUenlUSGU3UWVtR1V3REkKLS0tIE9tRUE1TkE4RDQ0NkFHVkpNejkw
            OVp1TUt5RVR2aTJGbUVYSEdCTUJ5Z1EKt6k1t5u4wf1977BaYt0UbWf/JfJTrVL6
            iG5LJlage887Mim8i7Rf74bPFiHEvDxGdlLGbiNfBSdq2/rMtBSHRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1srxf8entezg03y8n550g24w4se7gm7kdzzltcxfhckq7lek93vfsu2rpnw
    lastmodified: "2026-07-03T20:36:43Z"
    mac: ENC[AES256_GCM,data:vojEOvCSqDckrEhlo61WWCm/6AWDIQPBdkifKMeDORFlrRJSxjPGo7ZHudCebEbb6pydr5r/UU7RcZxv4XNRV9QWRe+NFkkO8EajDZpEtjcnH+48xi56yguZY7LhIjgDAmpMkBxtNS1LVnkwviNKyTNCzc3JQbbRIaZMOjKmayA=,iv:Z8V3C3REuxJ8ChsACK09SdTOWLxn5i7MOKw6Ovywk4M=,tag:7RaoG0luyIhWONbwANGjYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
