#ENC[AES256_GCM,data:4fjr+6GrpvuLaT0v6KV8ZJnsPndgXTS6vjckVihHD8Ktd8Se,iv:EZr2DaYOIH6y3fgsfKpBEzmwqbeABj6ygwhLC7u5P34=,tag:v4JCrpFqM0b06OeA7tNcLA==,type:comment]
#ENC[AES256_GCM,data:dbFtHtyEWLBIPG0yMR1NmI6tSHCUJuNs2nb/q29rAeNgPLFG,iv:E6C1S/k9rHbdZJ1OpLKPNutPyyBW5tOs7Uppvw6y0Mw=,tag:1GtbZ9tfZpF1jw7lw9kl7Q==,type:comment]
#ENC[AES256_GCM,data:VAluEMs+8BnGbo38y+XYTyMNsgTiBnzzfaCIsA==,iv:3+xMhsZt67VRVXMf4nKS0BJ/nD7f4ojKS2JOKL2HnRo=,tag:ZbRPKAesNvRz7KnPQH1x5Q==,type:comment]
root_password: ENC[AES256_GCM,data:RtZycZKExf6YFbfMF45rIX7t57OTaKC5d7LQWJdBnShS25oBseP02u9wiSF/NqdLIatEnyR8yQQalEYNX76t+Q==,iv:tV4evbU68yDH37rxVb40NidoLOOH3R27+RNklZ2PNG0=,tag:aZnEk9LpoWl8UwTpl1ZoLg==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:M65s02qjRqcXc/W4RQupSeA6nIDU,iv:ePbtekGng2EQa4BuTL9upZvR09kTVsyHAFseIIqWIwg=,tag:HSPrWtxdIls0OiWlh3lagA==,type:str]
#ENC[AES256_GCM,data:vipM6oy9PQsozLtY17pqMYts9oWEbIYPS0W3SGM=,iv:LwraPv92FL6aQRInck+Dr15hLhaDyz7DHcvSZShh+Fk=,tag:o3KKe6tCDfsp/ORUYfeUrw==,type:comment]
ansible_host: ENC[AES256_GCM,data:EO8ZnNyXS5TejedqejQmTQ==,iv:2dTNZY4+47XlcuhNLzeL4chuQ4OMCIj8YE9/RfpZlLU=,tag:JnjjSci2RxA99Bwtns0W8Q==,type:str]
request_ip: ENC[AES256_GCM,data:nSc1cHRIAXhobQ==,iv:RupAMnKZ290TJ1LnfDCuU2Q3dZYSXsurkGMXluhC7iU=,tag:M1n4WGH6C1SFOvnLiWuPyA==,type:str]
ansible_port: ENC[AES256_GCM,data:Xs3D+m0=,iv:GtumuWxWRTr0vedcK/R836b5GW8aK7QsBbaU2pPmCuY=,tag:P3x1dJwDdVdm+Aa+s/XXEQ==,type:int]
ansible_user: ENC[AES256_GCM,data:bORhRg==,iv:et5h77K9TCjDvs9LTX0TNkdoOSfgsbEmCCnppBJye4M=,tag:YnOVRbiPFspdN0PrVT6CSg==,type:str]
ansible_transfer_method: ENC[AES256_GCM,data:qwFO,iv:pbsFJ+U/LC7NVFmRiWZvck4SO+rXUVDEJx31ugpg4mE=,tag:lFv5OI7nIrvGkknveNgbnQ==,type:str]
ansible_scp_extra_args: ENC[AES256_GCM,data:nQM=,iv:lWaw9QF3SrzTgYLScY2JGUBMnXlQ59uCHz1QNrywbqs=,tag:vlTLaD2tp243/Cyz78lgOw==,type:str]
node_role: ENC[AES256_GCM,data:/yFY3TQrhA==,iv:hv7HF0MGoPmUPIjMQbfIxMaYWxUoE84Yo0L//eAbw/I=,tag:rRw9PLjb+BN0JvNv7kIycw==,type:str]
#ENC[AES256_GCM,data:D+Ie/ckA,iv:6ax4LXm2XeX2j2NbBpjxjQ9fQnKid7/6ysfmS4j3QkI=,tag:o7vx0xxK4jWF7VO7KFgvtQ==,type:comment]
blink_name: ENC[AES256_GCM,data:QLLwkVNFtr7TWdyt,iv:GJgjYdkMvrBkUM3Cc3P22DQnqKyxUWo3RryZ1uh5pPQ=,tag:3jWFaHfP021uvb6Nqv0Nng==,type:str]
color: ENC[AES256_GCM,data:rW+cSQy7kwNR,iv:W2mGQXsqg641QP96dugxi3k9HkZQJTBYpl4JMW5DwZ4=,tag:cCFXIe70dgU+vooDtn/gBw==,type:str]
interface: ENC[AES256_GCM,data:+1kQCA==,iv:1kQltX4grRWGK8cXnktP3P6+f61DFxCdNo6m2kSRam4=,tag:VY5mGZ7jIDVvjLAGDg61Ig==,type:str]
trigger: ENC[AES256_GCM,data:JZuD6BD0,iv:09IqnrJjFIn+IW5yNkIr4jpCcdHOeKh4A9I+oURfVik=,tag:pbQj+b8dQbiQpebn2NpU9A==,type:str]
change_uci_state: ENC[AES256_GCM,data:xGHJ,iv:9ogaXwyVVVTMxCVOCShwXxokGxK5xBmqzezTbctJ7FY=,tag:0gaH9UWdewZfetW8mfG/sw==,type:str]
led_mode: ENC[AES256_GCM,data:PoCDT8IPbAw=,iv:7zsl/ER0eTKMnXmF5s+oy2wgKH464jbpDDMBtv87Oao=,tag:q4mHoo99f2Dn5uIM99bVug==,type:str]
led_modes:
    - ENC[AES256_GCM,data:h+M=,iv:Vu21LAAeWiTzV67oycxrZ75z++KBwEICzYQ014eCT0M=,tag:E8S4WFz4UzcJjsTG3lSndg==,type:str]
    - ENC[AES256_GCM,data:J7w=,iv:XCMoyFw5dPtJ1xHyrWrM11bVsJ6Kfh6xhOXQLWAZpDY=,tag:nxNPxwMKQNZN3+5jD6MP8Q==,type:str]
ansible_private_key_file: ENC[AES256_GCM,data:VzUCScc4+F5+8V5XJrVGgkmMcsTcIpM/7BkKGhFnl13pdjEE+OIFxA==,iv:BVhh1VHFMuLEBWGCeVHOUeevcSNNT342pP8JARKblzE=,tag:vwZz6CXtVZhZFI/XQ/IIpw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ1RHeGp2L21UakIxWjZL
            bml3V0xPYXN1c0RQVXh4c0F3OXZKUk5QYW40CkRZQXhoWS9aeWNURndwVXhFNndo
            TkRIczlsZGVQZ1lELzQ4bVZQT2plbm8KLS0tIFJHbCtndEJGcnFRNGtDdWRSbG1W
            WmcwdlM1Zm94R1pKRzFpN3paRjFQR3MKKo/WJtVJvRKMgFvo4ONJd5Eu9Zq7FdNV
            BvQzY7SV4VMW3kXDNSp5tqnLy0JVOEAVxz8nRi2C86lQQFZYaYd31Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1srxf8entezg03y8n550g24w4se7gm7kdzzltcxfhckq7lek93vfsu2rpnw
    lastmodified: "2026-07-03T20:36:43Z"
    mac: ENC[AES256_GCM,data:ygMdsVKSafde/cuFwtiWxQs+G8/ysGy8GOmPowiF13shoRix4c3Pf7FtB7AF5b1kCXbJK/msMM5EgYL7LWcbqJ+47wz0KI54kN+DiOT40/l+hw7Lb2loXD4HpoUEieTK8jrYpt6mW0nn28GAC/bzxryTZKIgZE8NBzbsNhOJ1uE=,iv:k80ceUHOFjNv1x8zK45I0ZvIQf1aIQf7OmWVOFiek1Y=,tag:KOY+aJOKHofi1imYHKHNqw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
