#ENC[AES256_GCM,data:fChin26UHhuYlByPIP+yy0CMM6dwpbdWhYFAKpbaGwURWbBa,iv:JSQe1+Oxrvpn7Ri/Dx420chXrgTzgmmS4uTo41kTIms=,tag:Xf3vTtLplbIxXuXz/XLZaw==,type:comment]
#ENC[AES256_GCM,data:QapfjJqqHKYD20BU6bXYRYbHoBTegckMF3puwjrJTkpUkIuR,iv:Rr1enXgl+A0tuYl5XHJcZvDLD4HiBJaprBsFtQWqSqI=,tag:LQfXaIPYtX21+TtkJl663w==,type:comment]
root_password: ENC[AES256_GCM,data:BRS5WNbMz12cWVCpyaR5t0clJwP/v8GTqsudwvX8e6hjdz88doZg636WqAVjOgZ0EnVHN/TIOp5a7+ycHFRQ2w==,iv:1mJuy3TjvzEyaBfD7hjokZy+xtpmWWdSN4HeXD/YVxI=,tag:JjdcWfexddWeE+xSlLasJA==,type:str]
ansible_private_key_file: ENC[AES256_GCM,data:8daFfO9DCKBHsBrkmbStBW3cC1FbXvDntg==,iv:C4G+AUfMn9hKDNYJFeFZSkjVcw3YfSmKk/kW8qMXmHE=,tag:sD1jp6WcPftbpvg0uoVPvQ==,type:str]
ansible_host: ENC[AES256_GCM,data:tK2EfMGtKeZMObtkow==,iv:ob1jkSJdQZDtsUjN7+qvvR6eU9uHAqiU6VYLGCBjtZc=,tag:LKVAe+USyVkf7wr6v2X3zg==,type:str]
request_ip: ENC[AES256_GCM,data:fJ1NE/gtO4URAg==,iv:t8xdkp40FoMnWpY3hi9klPbffYZ5kFHxO6CzmQLpA/U=,tag:2tUeFr4MmtS/dLYZSNtZlA==,type:str]
ansible_port: ENC[AES256_GCM,data:66w+TxA=,iv:I602esoCwFEiaEN+UOVsN91LGklCKjEDpCU9wVGKIZ4=,tag:t8KVPt4+ZpHcDzML+YXP/w==,type:int]
ansible_user: ENC[AES256_GCM,data:bqYcMw==,iv:SATU9nFahdEVJH4gFMV4bl/4zUkOhw/6EZvg8GvjEjc=,tag:csxjhzDd6KBmesyGBGdMag==,type:str]
ansible_transfer_method: ENC[AES256_GCM,data:wt2J,iv:X5gHE1xBOHZrHNHbpuklNzNZJtUTQj2tgZDBCA9ZIP8=,tag:LGvZmDVw+qACi6yubvVH8g==,type:str]
ansible_scp_extra_args: ENC[AES256_GCM,data:pj0=,iv:Dab6g1Id0p+z7hagrKeKBAfbiWvkk9ye5TV7kYs8jiM=,tag:SDsElg/QqqNz0cP0v1BhkQ==,type:str]
node_role: ENC[AES256_GCM,data:CqKICwmS6g==,iv:nBL+osBIyWnCzYrKT3i2JYyCGkS3CPh+r8OSi5uPGWM=,tag:UwjSIxbYdRLXWGGGVP2izA==,type:str]
#ENC[AES256_GCM,data:V0dnUOGb,iv:yMksSeN6SZi9RdODKe+5wnQipZ0RnuLbP9MxQZzmcjA=,tag:IIKZoHE77s3CXV+xo4dtpw==,type:comment]
blink_name: ENC[AES256_GCM,data:zY8grrC4brnU5Obw,iv:/X2cFhD4+3JFE0Ways1nPy7HxGTNUrqDkBxwnuR4DRY=,tag:frW77dk0iZVx0CF1K0LilQ==,type:str]
color: ENC[AES256_GCM,data:uJFEo+0GCAI2QA==,iv:NgEGfgHh/Pa5jWD3e6PQgZ06oSaihTuRvd+8t9SDTTo=,tag:5B3gybORibwJ/zDRUp18Ow==,type:str]
interface: ENC[AES256_GCM,data:b7vzJA==,iv:5OhaSgyNRdAjbicZobd5kMHt+H7HMSIFv21UsPIIVGY=,tag:wTjzL2+s1JBBVoAj2lvHcA==,type:str]
trigger: ENC[AES256_GCM,data:MsS/1+ZK,iv:osP3icS8w5W6l7o5A0NdxVBHEmEbhYH1BjriyMTvI90=,tag:EFEqYN6T9HFQuAmFcMG6VA==,type:str]
change_uci_state: ENC[AES256_GCM,data:ijHN,iv:rTw13nPT0NPhoYWEUPj4N1y5vVvpJ+FpMuLGoBZoKZM=,tag:5Yu1qI5G/WrCncZ2F/+OHQ==,type:str]
led_mode: ENC[AES256_GCM,data:DlsZS27N7Zk=,iv:A3w6IRMCfmxhd8Q8Vqmyabd/Xz32b15DwkWO2eq1nhI=,tag:nRcqrs2TJzGVE2z+NOQ4+A==,type:str]
led_modes:
    - ENC[AES256_GCM,data:IKw=,iv:aRsFd9AQx968fQ7OvSp0UWzGpLM6nfqfpVFSDdZ1NBg=,tag:beGQ6r1RWeW7qTyTgkjWRw==,type:str]
    - ENC[AES256_GCM,data:Blk=,iv:nOOMWXQ8UPQHkk4Necuy0DOR+D7YoDOeIYf2VgNIuCc=,tag:owA3EQQkHQDEUyKE7sTz1A==,type:str]
sops:
    age:
        - recipient: age1srxf8entezg03y8n550g24w4se7gm7kdzzltcxfhckq7lek93vfsu2rpnw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEeDZSYzVOckJFaDUxT0Qr
            Skc2S2RJamNFTHBSekZLc0hidEFHMlhHdndZClR0N1VxZW9adkxxZ2xWSzNDM1Y0
            eGpITmd3dGJ2MDFDWHVoZ2FISW9QS1EKLS0tIFRhT0hOck1zN0pHRjR3a1Z0THk1
            WU1xcXZQbmd3ZkI1SUo3WXBFcEZBck0KMbXTxLco3doM9BQ0WcSsVcSrpTCZVdwH
            daNvlyEEkt1YCVdt0rkSUE3W7hjlE6brdfP3B4aDg7gHY7E+ELD8Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T18:25:44Z"
    mac: ENC[AES256_GCM,data:OXzyjPw1r3p0uenUhwO7mXy8w+BkKu0uyRe0kNr1REneHHpFurH5bpeiixcKF+2Hsc3drFDMw+I10iSfdBgMIAj2U/xA0vqoh59MtuExAtGn4SePEsJWe90LRnjZg3hy9pgOESnjsWp2O9dBjeLWrhknUEDcG4EfP1uSrF/0Pgo=,iv:Qp0KZYkBIbMTORPTi7o6u6C7Unyff6SIbjWOcCB66OQ=,tag:I38Vq16+6kN0nnAk/yEBwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
