all:
  children:
    wazuh_agents:
      hosts:
        donator_clash_redhat_server:
        impolite_illusive_redhat_workstation:
        reptilian_attest_debian_workstation:
        overfed_patriot_windows_workstation:
        windows_2:
        daisy_dc:
        annotate_dc:
    wazuh_managers:
      hosts:
        main_server:
    servers:
      children:
        wazuh_managers:
          hosts:
    domain:
      children:
        domain_members:
          children:
            linux_domain_members:
              hosts:
                donator_clash_redhat_server:
                impolite_illusive_redhat_workstation:
                reptilian_attest_debian_workstation:
            windows_domain_members:
              hosts:
                overfed_patriot_windows_workstation:
                windows_2:
        domain_controllers:
          children:
            windows:
              hosts:
                daisy_dc:
                annotate_dc:
