join_method: ENC[AES256_GCM,data:aBkmIc4=,iv:0WSyLsk75NBHgMAuTT2uE4BzhzfzzY5wmgYGWr7Abu8=,tag:7I5hKtbliEsS+bMQfl0TwA==,type:str]
domain_netbios: ENC[AES256_GCM,data:GLLrhscr8n8=,iv:pxxGy7bLvbBaIdcK8j5wWKnU324vKScp1SY+kgtvL1Y=,tag:ooXRVNKX1vxElqDZroCRew==,type:str]
offline_password: ENC[AES256_GCM,data:oD6bY4Wve8mufeNFde6qSXmA,iv:MOzhCpSOml7EQCYiQ17MYeKlAlGoTZ8kwNC3D52YJIA=,tag:efL39pTxx9+I3GsCSgiotg==,type:str]
domain_name: ENC[AES256_GCM,data:ofY+l34xvHQj,iv:DwHlltAwJJBAuAiYALcwmh5H375F1O9FLLaCtbzPwbo=,tag:qw+gcAFBAcvfs0Ji8Qr7ng==,type:str]
domain_structure: ENC[AES256_GCM,data:JiLxLkfAtmMKeX8WgSC7,iv:oJ7Ilh/ho5yScYGKZge7KL7SbiYbBXuueJIZKvjTyZU=,tag:Zda5tIq+GnoJrQ47gz0X+A==,type:str]
sudoers_path: ENC[AES256_GCM,data:PurlI5BwJumTCMeSdkMSF1UhM/8DlSAAhD8=,iv:gZPwBmcKWeB1Y+9M5yjQZMb/YtFwqdOv8/73KqErgrs=,tag:99fYRCtOxzLE1uCP5XVLng==,type:str]
domain_admin: ENC[AES256_GCM,data:tr32Uijd48D6iUnTBg==,iv:Cxg3X19QwUlNAorrmoGC0WqJH9vB1GbunCxQ1lqkUL4=,tag:gmDZ7BlVd0Bt84/Yaa+bdQ==,type:str]
domain_admin_password: ENC[AES256_GCM,data:+92GIJ6TBsrC7TCAg2rEd+C5PDpM7U5ozKE=,iv:lgLZ5hmzJGoH2FDnavy3ArvYfA6gw+3TC8HEsr1Xzco=,tag:6d1hvEPav/N/SQE24hkexA==,type:str]
login_policy: ENC[AES256_GCM,data:jQpmYmJsuCc=,iv:ICxFfvPOCc8+sXVQWwxd9hJfTpoWByYbcpOL3J4xx1c=,tag:xewtwcQDt9zd3d4ca1BOTQ==,type:str]
allowed_groups: ENC[AES256_GCM,data:pF8QF0kEpCthXA==,iv:UIX5EcdC54LuL1KokCTHeicQ5nIWBEBp4co/yjPAdJw=,tag:fXTLYMmtkva+UC/ipHGh/A==,type:str]
sudoers_group: ENC[AES256_GCM,data:CcSdfeDNiNMtVQY=,iv:sXR3PKgyOFsgomNKvLaMHF83f9Kh6ecbfb4N2nVB7Kg=,tag:lWq1PTEjHh8xejXd2b2PjA==,type:str]
artifacts_dir: ENC[AES256_GCM,data:W0mFfe3/Mz6dd3IXHyM0OeAaPe1vaPgmQf15rEVFwIzlAE68yMgfOFBPdHNg+sh8b2rWotO2o2kwSaLiVLw0JAtcwubTNnXB/O12riw=,iv:ucXxTlfG0qd6CFqjZm557jwRNcPqOmsvXTDv3xgzH4Q=,tag:CT7A56SRYWWd9MRj3vfSgA==,type:str]
sudo_governance: ENC[AES256_GCM,data:zjcQh+ep,iv:Ofh5rskkjWsiC6maM8DrO71Ix35TfBccjbqWZ8X2Oq4=,tag:WSA9eyTziAkEoUKoV27H/g==,type:str]
alloy_ip: ENC[AES256_GCM,data:b6Zby6eBI5sU/A==,iv:oOc/fKoZBG5sT1M5yyRNoAoNEDEWKh+mRrykUqYHvdc=,tag:RxBEbb7vt+s6zIJpIu7N6g==,type:str]
alloy_port: ENC[AES256_GCM,data:bLak+d8=,iv:2FM/SetByGClZpjNzfWV49uVFPxBtwlfv7G/IqwvL6w=,tag:22pCBwWJ+wEaB7tgdNWRnA==,type:int]
alloy_config_path: ENC[AES256_GCM,data:2rFj3Fj36Tk9+f+5VXnewu8vlVLZEyppcnXa3nK9uLJTHnS8g11XND2srQdOUHOg,iv:rO0cBK6NWujx3WpV/oP3KMCWIc8wZDtp+DFQT9RYYRs=,tag:TeUDFYVpD0MYJ697qy0h0A==,type:str]
wazuh_manager: ENC[AES256_GCM,data:75Nf62eaQqQfnQ==,iv:XgCCYL805I8Uta/XtGHk/TVZJzSNHhP70eiNaqwF79w=,tag:q/anudRMVsp5Z7FRzLHTJw==,type:str]
wazuh_port: ENC[AES256_GCM,data:9reynw==,iv:ID2XR8O45YcZ8ZUNftVgvAqFBdyB9DRHaHEPEpan6bU=,tag:MsaPZnF6dq8/mVpUCv3F/w==,type:int]
wazuh_registration_port: ENC[AES256_GCM,data:Pr+zCA==,iv:DH+3zHTayVm8vpZ4NZu+EBpQtxbqkSRvl/J6gUPsJlk=,tag:W5KYAEj3Y2FcNrPs54Uttg==,type:int]
prometheus_push_url: ENC[AES256_GCM,data:RMwIFTnj9VzDBCfq0voVVSS2/B/e1ql25Vq4Esn99ehcL/8=,iv:VNNVXzWOuPMNmGmBqitEw8f5zRTurnw+A/tnTvZps2g=,tag:gAn7T35FyrFMheP0YK6RLg==,type:str]
loki_port: ENC[AES256_GCM,data:phZn8w==,iv:lonFrx8QAq/W3+qV0JS3DSjfU/XfqmWU5+yWoQdlU3M=,tag:uYWV/PjlqEZ9L1urX2sI1Q==,type:int]
loki_push_url: ENC[AES256_GCM,data:6hyWYsFy6APUjfKDOZqCEsLfNcqnO9WA2zNHD20N6o+OZIs/U1Pl,iv:sp6ruhgdS0ftzUS9QhBUf+xf8q8WsQhGU3/WuaLHkf8=,tag:7c5v2MoMpcS3RgAOd3BS7w==,type:str]
klist_user: ENC[AES256_GCM,data:jp3+vQvfzj7t,iv:88At7tI3JOTaEQs4qk0RXv46jwO8r9Xj9mMMs/Iq4SA=,tag:vYkO16YyoAESALmQIc7mAg==,type:str]
klist_password: ENC[AES256_GCM,data:UFuqSwziAJFSwtqjYb9F5WE=,iv:VuWauexiDpNUGKoNozPj86AH38HXZbExYqHodIKV9h4=,tag:rMn+PGxN3UdQOtDCd+vZaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeG9tcXE0WFJVbHVmUnpY
            ZFFGUSs1VDlQTE5ObDlqeTlRbUY1WWtXT3o0CmtYbWJMc0ViRHgwdFNLZ1J6NkJo
            eWZFUFFkQVd5VmlDdDRkUXBKQTd6RzgKLS0tIGZPNlBhL1V6TkdwSjI5aE9vNmRP
            MDFJNFZhd0pwb2k0aXdIZVlNSXF3UTAKT9mVAneCZh4I7M0vOgLv/6fssJIEZOG7
            l/PFnSTnO995bGsWnF+RNwCEcigUqJtU+0qZWitViq+8utWeM5Y45w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1srxf8entezg03y8n550g24w4se7gm7kdzzltcxfhckq7lek93vfsu2rpnw
    lastmodified: "2026-08-01T18:00:15Z"
    mac: ENC[AES256_GCM,data:OJzHAfiK+Fa5JRIfQw5xZMYc7ZiNOappKxZj0QOcAu0uR74vN3fKo45REDQsR+B84A/ZkZYRgDhvo4jlKcaxa4hiCeyxmKkAvqm094Ysws0m0QPphBEBZUgzKwPDmG3tTwcnL9hMgek+tInMC8J7sYA2awg9y4mNuIlE+YdVLDk=,iv:63Fqp9RK40MCoytBjWu9ai9nuD0gWZ0tCHOSP2XR3hM=,tag:G44xHcyX5IZgH54y0qNbXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
